apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
  namespace: microservices
  labels:
    app: loginapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
        - name: loginapp
          image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/loginapp:e974ef2521346366a68f88f098c6ad30a15e91d3
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
namespace: microservices
metadata:
  name: loginapp-service
spec:
  type: NodePort
  selector:
    app: loginapp
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 3001  # Container port
      nodePort: 30081   # NodePort (range 30000â€“32767)

