apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapp
  namespace: microservices
  labels:
    app: cartapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      containers:
        - name: cartapp
          image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/cartapp:e974ef2521346366a68f88f098c6ad30a15e91d3
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: cartapp-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: cartapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30080

##