apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapp
  labels:
    app: cartapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      containers:
        - name: cartapp
          image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/cartapp:9464053374829a79347140becef732d6703e07d2
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: cartapp-service
spec:
  type: NodePort
  selector:
    app: cartapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30080

##