apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentapp
  namespace: microservices
  labels:
    app: paymentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymentapp
  template:
    metadata:
      labels:
        app: paymentapp
    spec:
      containers:
        - name: paymentapp
          image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/paymentapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: paymentapp-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: paymentapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 30082

